---

networks:
  stack:

volumes:
  postgres_data:
    driver: local
  mftserver_file_data:
    driver: local
  mftserver_is_configs:
    driver: local
  mftserver_mft_configs:
    driver: local

services:

  mftserver:
    image: ${REG_MFTSERVER}${REPO_MFTSERVER}:${TAG_MFTSERVER}
    restart: ${RESTART_POLICY_RUNTIMES}
    ports:
      ## webMethods IntegrationServer Runtime Ports
      - 5555:5555
      - 5543:5543
    environment: 
      SCRIPTS_LOGGER_LEVEL: "1"
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 2g
      JAVA_OPTS: "-server -Dtest=1 -Dtes2=2 -Dtest3=3"
    volumes:
      - mftserver_is_configs:/opt/softwareag/IntegrationServer/instances/default/config:rw
      - mftserver_mft_configs:/opt/softwareag/IntegrationServer/instances/default/packages/WmMFT/config:rw
      - mftserver_file_data:/data:rw
      - ./replicate_mftserver:/opt/softwareag/IntegrationServer/instances/default/replicate:rw
    hostname: mftserver
    networks:
      - stack
    depends_on: 
      - postgres

  dbconfig:
    image: ${REG_DBCONFIG}${REPO_DBCONFIG}:${TAG_DBCONFIG}
    restart: ${RESTART_POLICY_JOBS}
    environment: 
      SCRIPTS_LOGGER_LEVEL: 1
      DB_ACTION: create
      DB_TYPE: POSTGRESQL
      DB_NAME: webmisdb
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: webmisdb
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_JDBC_URL: ""
      DB_JDBC_ARGS: ""
      PRODUCT_VERSION: 10.15
      PRODUCT_NAMES: IS,MWS,Monitor
      COMPONENT_NAMES: ActiveTransfer,ActiveTransferArchive,Archive
      RUN_FINAL_INVENTORY: "true"
      WAITFOR_DB_HOST: "true"
      WAITFOR_DB_TIMEOUT_SEC: "30"
    networks:
      - stack
    depends_on: 
      - postgres

  postgres:
    image: ${REPO_POSTGRES}
    restart: ${RESTART_POLICY_RUNTIMES}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: webmisdb
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - stack