---

networks:
  stack:

volumes:
  postgres_data_mft:
    driver: local
  postgres_data_mftarch:
    driver: local
  mftserver_file_data:
    driver: local
  mftserver_is_configs:
    driver: local
  mftserver_mft_configs:
    driver: local

services:

  mftserver:
    image: ${REG_MFTSERVER}${REPO_MFTSERVER}:${TAG_MFTSERVER}
    restart: ${RESTART_POLICY_RUNTIMES}
    platform: linux/amd64
    hostname: mftserver
    ports:
      ## webMethods IntegrationServer Runtime Ports
      - 5555:5555
      - 5543:5543
    environment:
      SAG_IS_ADMIN_PASSWORD: ${MFT_ADMIN_PASSWORD}
    volumes:
      - ./application.properties:/opt/softwareag/IntegrationServer/application.properties
      - mftserver_file_data:/data:rw
      # - ./replicate_mftserver:/opt/softwareag/IntegrationServer/instances/default/replicate:rw
      # - mftserver_is_configs:/opt/softwareag/IntegrationServer/instances/default/config:rw
      # - mftserver_mft_configs:/opt/softwareag/IntegrationServer/instances/default/packages/WmMFT/config:rw
    networks:
      - stack
    depends_on:
      - database
      - database-archive

  dbconfig:
    image: ${REG_DBCONFIG}${REPO_DBCONFIG}:${TAG_DBCONFIG}
    restart: ${RESTART_POLICY_JOBS}
    platform: linux/amd64
    environment: 
      DB_ACTION: create
    volumes:
      - ./db_postgres_demo:/opt/softwareag/common/auth/db:ro
    networks:
      - stack
    depends_on:
      - database
      - database-archive

  database:
    image: postgres:12
    restart: ${RESTART_POLICY_RUNTIMES}
    hostname: database
    volumes:
      - postgres_data_mft:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mftdbuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mftdb
    networks:
      - stack

  database-archive:
    image: postgres:12
    restart: ${RESTART_POLICY_RUNTIMES}
    hostname: databasearchive
    volumes:
      - postgres_data_mftarch:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mftarchivedbuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mftarchivedb
    networks:
      - stack